Repository Gagan-Space/Cansat-Ground-Station, pull requests merged in 2024-06, with the labels that each got.

#92 MAVLink Decoding and Parsing Integration
  package.json
  src/server.js
  yarn.lock
Labels: enhancement 🪄, For Discussion 📣, Migration ✈

#102 Added Documentation
  mkdocs/Docs/faq.md
  mkdocs/Docs/gettingstarted.md
  mkdocs/Docs/index.md
  mkdocs/Docs/test.md
  mkdocs/Docs/tutorial.md
  mkdocs/mkdocs.yml
Labels: documentation 📖

#105 Update README.md
  README.md
Labels: documentation 📖, enhancement 🪄

#107 feat: add pr title checker workflow
  .github/pr-title-checker.json
  .github/workflows/pr-title-checker.yml
Labels: gssoc, level1, Automation 🤖

#117 Issue resolved for contributors name
  README.md
Labels: documentation 📖, gssoc, level1

#119 added preloader
  package-lock.json
  package.json
  src/Assets/preloader.json
  src/components/Preloader/Preloader.css
  src/components/Preloader/Preloader.tsx
  src/main.tsx
  yarn.lock
Labels: enhancement 🪄, gssoc, level2
