Repository Gagan-Space/Cansat-Ground-Station, pull requests merged in 2024-05, with the labels that each got.

#20 Start-Mission
  src/app/store.jsx
  src/components/CSVexporter/CSVgenerator.js
  src/components/CSVexporter/UI/ExportButton.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Serial/Serial.js
  src/components/Serial/UI/ConnectButton.jsx
  src/components/StartMission/StartMission.js
  src/components/StartMission/UI/StartMission.jsx
  src/features/configs/connectedSlice.jsx
  src/features/mission-state/launchSlice.jsx
Labels: enhancement 🪄

#25 Added : Learn.md
  Learn.md
Labels: GSSoC'24 🧠

#40 Added comments to code files
  .storybook/main.js
  .storybook/preview.js
  src/App.jsx
  src/app/store.jsx
  src/components/CSVexporter/CSVgenerator.js
  src/components/CSVexporter/UI/ExportButton.jsx
  src/components/InstrumentCluster/AirSpeed/AirSpeed.jsx
  src/components/InstrumentCluster/Altimeter/Altimeter.jsx
  src/components/InstrumentCluster/Compass/Compass.jsx
  src/components/InstrumentCluster/Heading/Heading.jsx
  src/components/InstrumentCluster/VerticalSpeed/VerticalSpeed.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Rocketmodel/Rocketmodel.jsx
  src/components/Serial/Serial.js
  src/components/Serial/UI/BaudSelector.jsx
  src/components/Serial/UI/ConnectButton.jsx
  src/components/StartMission/UI/StartMission.jsx
  src/features/configs/baudrateSlice.jsx
  src/features/configs/connectedSlice.jsx
  src/features/mission-state/launchSlice.jsx
  src/features/telemetry/TelemetrySlice.jsx
  src/main.jsx
  src/stories/AirSpeed.stories.jsx
  src/stories/Altimeter.stories.jsx
  src/stories/Compass.stories.jsx
  src/stories/ExportButton.stories.jsx
  src/stories/Heading.stories.jsx
  src/stories/SerialDataReader.stories.jsx
  src/stories/VerticalSpeed.stories.jsx
Labels: documentation 📖, gssoc, level1

#41 [Bug] : Responsive issues can fixes
  src/App.css
  src/App.jsx
Labels: bugfixes 🐞, gssoc, level1

#48 Mk docs
  .github/workflows/build.yaml
  .github/workflows/mkdocs.yaml
  .gitignore
  mkdocs/Docs/test.md
  mkdocs/mkdocs.yml
  mkdocs/requirements.txt
Labels: documentation 📖, gssoc, level3

#52 Create greetings.yaml
  .github/workflows/greetings.yaml
Labels: gssoc, level2, Automation 🤖

#51 Homepage
  package-lock.json
  package.json
  src/App.jsx
  src/Home.css
  src/Home.jsx
  src/Station.css
  src/Station.jsx
  src/ViewButton.jsx
  src/main.jsx
Labels: enhancement 🪄, gssoc, level2

#59 Electron transition
  .github/CODEOWNERS
  .github/workflows/build.yaml
  .github/workflows/greetings.yaml
  .github/workflows/mkdocs.yaml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  electron/electron.js
  electron/preload.js
  index.html
  mkdocs/Docs/test.md
  mkdocs/mkdocs.yml
  mkdocs/requirements.txt
  package-lock.json
  package.json
  src/App.tsx
  src/app/store.tsx
  src/components/CSVexporter/CSVgenerator.ts
  src/components/CSVexporter/UI/ExportButton.tsx
  src/components/InstrumentCluster/AirSpeed/AirSpeed.tsx
  src/components/InstrumentCluster/Altimeter/Altimeter.tsx
  src/components/InstrumentCluster/Compass/Compass.tsx
  src/components/InstrumentCluster/Heading/Heading.tsx
  src/components/InstrumentCluster/VerticalSpeed/VerticalSpeed.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Rocketmodel/Rocketmodel.tsx
  src/components/Serial/Serial.js
  src/components/Serial/Serial.ts
  src/components/Serial/UI/BaudSelector.tsx
  src/components/Serial/UI/ConnectButton.tsx
  src/components/StartMission/StartMission.ts
  src/components/StartMission/UI/StartMission.tsx
  src/features/configs/baudrateSlice.tsx
  src/features/configs/connectedSlice.tsx
  src/features/mission-state/launchSlice.tsx
  src/features/telemetry/TelemetrySlice.tsx
  src/main.tsx
  src/stories/AirSpeed.stories.tsx
  src/stories/Altimeter.stories.tsx
  src/stories/Compass.stories.tsx
  src/stories/ExportButton.stories.tsx
  src/stories/Heading.stories.tsx
  src/stories/SerialDataReader.stories.tsx
  src/stories/VerticalSpeed.stories.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement 🪄, gssoc, level3, Migration ✈

#64 Added CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: gssoc, level1, Automation 🤖

#66 docs: added issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc, level1, Automation 🤖

#69 Added pull_request_template.md
  .github/pull_request_template.md
Labels: gssoc, level1, Automation 🤖

#70 Added an route for data analysis page
  package-lock.json
  package.json
  src/App.tsx
  src/components/Analysis/Analysis.ts
  src/components/Analysis/UI/Analysis.tsx
  src/components/Analysis/UI/AnalysisButton.tsx
  src/components/Analysis/UI/PloteGraph.tsx
  src/components/MainLanding/UI/MainLanding.tsx
  src/components/Navbar/Navbar.tsx
Labels: enhancement 🪄, gssoc, level3

#82 Added devcontainer , github action workflow to test dockerfile and dockercompose up
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .dockerignore
  .github/workflows/docker-build.yml
  Dockerfile
  README.md
  docker-compose.yml
  vite.config.ts
Labels: enhancement 🪄, gssoc, level3

#86 Migrated to yarn
  .github/workflows/build.yaml
  Learn.md
  README.md
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement 🪄, Migration ✈

#88 feat: add codeql workflow for typescript
  .github/workflows/codeql.yml
Labels: gssoc, level1, Automation 🤖
